bilibili_cookie:
  bili_jct: "ec30ef198c6f52a3595c4c33e8b61e05"
  ac_time_value: "095a510a9714dca6fe9405f755c98d91"
  buvid3: "6E99731B-F97B-A314-6B7C-DFBB84764ED983756infoc"
  SESSDATA: "cd7ec8c2%2C1711633323%2C4ed5b%2A91CjBxkV0omxjiuBKRZrL6T-rM_04FVZWhiGBzFX_FXKgFYDZ3gW6PhTXAWWEj57iBKPwSVnZueTl6UFlsazRpaHE5T19zenJWSTNWQnNOMmI3dXZ0Tm9LUkdpOXFFR2V2UFpvYmZZejd0azNHVHA5bkFFMnR6RjlmbnNZUnVHOW5HWlRzLUJsdmhnIIEC"
  dedeuserid: "6280028"

keywords:
  summarize-keywords: # 用于生成摘要的关键词，如果at/私信内容包含以下关键词，将会生成摘要
    - "总结"
    - "总结一下"
    - "总结一下吧"
    - "总结一下吧！"
  evaluate-keywords: # 用于生成评价的关键词，如果at/私信内容包含以下关键词，将会生成评价（该功能开发中）
    - "锐评视频"
    - "锐评"
    - "锐评一下"
    - "锐评一下吧"
    - "锐评一下吧！"


openai:
  api-key: "mk-0fNJ9BxvtXJNQYBtsC3Q6sg9J3k12cdEsnCBQdAaDkqSrosq" # 你的openai api key
  api-base: "https://api.aiproxy.io/v1" # 你的openai api base url（多数在使用第三方api供应商时会有，记得url尾缀有/v1）
  model: "gpt-3.5-turbo-16k" # 选择模型，我现在只推荐使用gpt-3.5-turbo-16k，其他模型容纳不了这么大的token，如果你有gpt-4-16k权限，还钱多，请自便
  max-total-tokens: null # 一次运行最多使用的token，耗尽后程序停止（只会计算生成摘要和重试的token，whisper后处理的token不会被计算）

whisper:
  whisper-enable: false # 是否启用whisper，在视频无字幕时生成字幕，否则该视频将自动跳过
  whisper-model-size: "base" # tiny, base, small, medium, large 详细选择请去：https://github.com/openai/whisper
  whisper-device: "cuda" # cpu or cuda（仅在运行源代码时可用，docker运行只能选择cpu）
  whisper-after-process: false # 是否在使用whisper转义后再使用llm优化生成结果，最终字幕效果会大幅提升
  whisper-model-dir: "./my-config/whisper-models" # 本地模型存放目录，如果更改要映射出来

temp-dir: "./my-config/temp" # 主要用于下载视频音频生成字幕，如果更改要映射出来
cache-path: "./my-config/cache.json" # 用于缓存已经处理过的视频，如果更改要映射出来
task-status-records: "./my-config/records.json"
statistics-dir: "./my-config/statistics" # 用于存放统计数据，如果更改要映射出来